/**
 * The Catalog: the reviewed set of known Cloud Endpoints, snapshotted from the
 * community-maintained models.dev database.
 *
 * This file is source code and is reviewed as such. It decides which address a
 * Credential is sent to, so a changed base URL has to arrive as a diff rather
 * than silently over the network. Nothing fetches models.dev at runtime: a live
 * catalog would make credential forwarding depend on a third party's integrity
 * on every request.
 *
 * Regenerate with `node scripts/refresh-catalog.mjs <models.dev-api.json>`, then
 * review the diff before committing it. validateCatalog() checks the result
 * before anything is allowed to send a Credential anywhere.
 *
 * The Credential variable names below are HAND-MAINTAINED from here on, not the
 * snapshot's. Regenerating from models.dev would reintroduce nine variables
 * that each reach more than one host — ZHIPU_API_KEY, MOONSHOT_API_KEY,
 * DASHSCOPE_API_KEY, KIMI_API_KEY, STEPFUN_API_KEY, XIAOMI_API_KEY and the
 * Alibabas — because models.dev conflates each vendor's international and
 * Chinese services under one name while listing them at genuinely different
 * addresses. Those are separate accounts holding separate Credentials: entering
 * one of those variables through the interface would Configure four Endpoints
 * and proxy the value to two companies' servers, one of them a .cn host. That
 * is precisely the outcome the Catalog is reviewed to prevent, so the variable
 * name is the part of this file this project owns rather than inherits.
 *
 * scripts/refresh-catalog.mjs carries the same renames so a re-snapshot lands
 * here directly, and validateCatalog() fails the load if any variable ever
 * spans two hosts again. Entries sharing one variable AND one host —
 * llmgateway with llmgateway-providers, opencode with opencode-go — are the
 * same Credential listed twice, and are left shared.
 *
 * What this snapshot covers, and what it leaves out:
 *
 * Every Cloud Endpoint here is addressed in the OpenAI chat format, because one
 * integration drives them all and a per-provider adapter is out of scope. Most come
 * from models.dev's own `npm: "@ai-sdk/openai-compatible"` flag; OpenRouter and the
 * `@ai-sdk/openai` gateways serve the same request body.
 *
 * - 32 left out: they answer in a format of their own.
 * - 5 left out: their base URL is a `${...}` template awaiting an
 *   account-specific value, and completing one would mean guessing where a Credential is sent.
 * - 4 left out: loopback addresses, which are Local Endpoints. The Catalog does
 *   not cover Local Endpoints; they are declared by hand in registry.ts. Ollama, the local
 *   server this app is built around, is absent from models.dev entirely.
 * - 4 written out by hand rather than snapshotted: OpenAI, Gemini, Groq and
 *   Mistral each publish a first-party SDK rather than the compatibility one, and three of
 *   them carry no base URL in models.dev at all. Each is marked `handAdded` below so a
 *   reviewer can tell a hand-written address from a snapshotted one at a glance.
 * - Each provider keeps its 5 newest text-output Models. The full listing is
 *   several megabytes, and Model Discovery asks an Endpoint for its live Models anyway.
 */

import type { CatalogEntry } from "./types";

export type { CatalogEntry };

/** The snapshot itself, filtered by the refresh script and nothing else. */
export const CATALOG: readonly CatalogEntry[] = [
  {
    id: "302ai",
    name: "302.AI",
    baseURL: "https://api.302.ai/v1",
    credentialEnvVar: "302AI_API_KEY",
    doc: "https://doc.302.ai",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "claude-sonnet-5-5",
      "claude-opus-5-5",
      "gpt-6-luna",
      "gpt-6-sol",
      "grok-4.7",
    ],
  },
  {
    id: "abacus",
    name: "Abacus",
    baseURL: "https://routellm.abacus.ai/v1",
    credentialEnvVar: "ABACUS_API_KEY",
    doc: "https://abacus.ai/help/api",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "gemini-3.7-flash",
      "grok-4.6",
      "muse-spark-1.2",
      "qwen3.8-max",
      "claude-opus-5",
    ],
  },
  {
    id: "abliteration-ai",
    name: "abliteration.ai",
    baseURL: "https://api.abliteration.ai/v1",
    credentialEnvVar: "ABLIT_KEY",
    doc: "https://docs.abliteration.ai/models",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "abliterated-model-large-v2",
      "abliterated-model-large",
      "abliterated-model",
    ],
  },
  {
    id: "above",
    name: "above.dev",
    baseURL: "https://api.above.dev/v1",
    credentialEnvVar: "ABOVE_API_KEY",
    doc: "https://above.dev/docs",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "mimo-v2.6-flash",
      "mimo-v2.6-pro",
      "mimo-v2.6-pro-ultraspeed",
      "deepseek-v4-flash",
      "deepseek-v4.1-flash",
    ],
  },
  {
    id: "agentrouter",
    name: "AgentRouter",
    baseURL: "https://agentrouter.org/v1",
    credentialEnvVar: "AGENTROUTER_API_KEY",
    doc: "https://agentrouter.org/docs/opencode.html",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "glm-5.3",
      "claude-opus-5",
      "gpt-5.6-sol",
      "claude-opus-4-8",
      "deepseek-v4-flash",
    ],
  },
  {
    id: "agnes",
    name: "Agnes AI",
    baseURL: "https://apihub.agnes-ai.com/v1",
    credentialEnvVar: "AGNES_API_KEY",
    doc: "https://agnes-ai.com/doc",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "agnes-2.5-pro-alpha",
      "agnes-2.5-flash",
      "agnes-2.0-flash",
    ],
  },
  {
    id: "ai-router",
    name: "AI-ROUTER",
    baseURL: "https://api.ai-router.dev/v1",
    credentialEnvVar: "AI_ROUTER_API_KEY",
    doc: "https://ai-router.dev/openai-compatible-api-gateway/",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "gpt-5.6-luna",
      "gpt-5.6-sol",
      "gpt-5.6-terra",
      "gpt-5.5",
      "gpt-5.4",
    ],
  },
  {
    id: "aiand",
    name: "ai&",
    baseURL: "https://api.aiand.com/v1",
    credentialEnvVar: "AIAND_API_KEY",
    doc: "https://docs.aiand.com/",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "deepseek-ai/deepseek-v4.1-flash",
      "zai-org/glm-5.3-flash",
      "qwen/qwen3.8-27b",
      "zai-org/glm-5.3",
      "motif-technologies/motif-3",
    ],
  },
  {
    id: "ai21",
    name: "AI21 Labs",
    baseURL: "https://api.ai21.com/studio/v1",
    credentialEnvVar: "AI21_API_KEY",
    doc: "https://docs.ai21.com/docs/jamba-foundation-models",
    capabilities: ["toolCalling", "structuredOutput"],
    knownModels: [
      "jamba-mini",
      "jamba-large",
    ],
  },
  {
    id: "ainetcafe",
    name: "ainetcafe",
    baseURL: "https://microquickjs.com/v1",
    credentialEnvVar: "AINETCAFE_API_KEY",
    doc: "https://ainetcafe.com/k3/guides/",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "Kimi-K3",
    ],
  },
  {
    id: "aixy",
    name: "Aixy",
    baseURL: "https://api.aixy-gateway.com/v1",
    credentialEnvVar: "AIXY_API_KEY",
    doc: "https://docs.aixy-gateway.com/integrations/overview",
    capabilities: ["toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "openai/gpt-4.1-mini",
    ],
  },
  {
    id: "aki-io",
    name: "AKI.IO",
    baseURL: "https://aki.io/v1",
    credentialEnvVar: "AKI_IO_API_KEY",
    doc: "https://aki.io/docs/",
    capabilities: ["reasoning", "toolCalling", "structuredOutput"],
    knownModels: [
      "deepseek-v4.1-flash-552b",
      "glm5.3-754b",
      "qwen3.8-27b",
      "qwen3.6-35b",
      "gemma4-26b",
    ],
  },
  {
    id: "alibaba",
    name: "Alibaba",
    baseURL: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
    credentialEnvVar: "DASHSCOPE_API_KEY",
    doc: "https://www.alibabacloud.com/help/en/model-studio/models",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "qwen3.8-omni-flash",
      "qwen3.8-flash",
      "qwen3.8-max",
      "deepseek-v4-flash-0731",
      "kimi-k3",
    ],
  },
  {
    id: "alibaba-cn",
    name: "Alibaba (China)",
    baseURL: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    credentialEnvVar: "DASHSCOPE_CN_API_KEY",
    doc: "https://www.alibabacloud.com/help/en/model-studio/models",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "qwen3.8-omni-flash",
      "deepseek-v4.1-flash",
      "qwen3.8-flash",
      "glm-5.3",
      "qwen3.8-max",
    ],
  },
  {
    id: "alibaba-coding-plan",
    name: "Alibaba Coding Plan",
    baseURL: "https://coding-intl.dashscope.aliyuncs.com/v1",
    credentialEnvVar: "ALIBABA_CODING_PLAN_API_KEY",
    doc: "https://www.alibabacloud.com/help/en/model-studio/coding-plan",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "qwen3.7-plus",
      "qwen3.6-plus",
      "qwen3.5-plus",
      "MiniMax-M2.5",
      "glm-5",
    ],
  },
  {
    id: "alibaba-coding-plan-cn",
    name: "Alibaba Coding Plan (China)",
    baseURL: "https://coding.dashscope.aliyuncs.com/v1",
    credentialEnvVar: "ALIBABA_CODING_PLAN_CN_API_KEY",
    doc: "https://help.aliyun.com/zh/model-studio/coding-plan",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "qwen3.7-plus",
      "qwen3.6-plus",
      "qwen3.5-plus",
      "MiniMax-M2.5",
      "glm-5",
    ],
  },
  {
    id: "alibaba-token-plan",
    name: "Alibaba Token Plan",
    baseURL: "https://token-plan.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1",
    credentialEnvVar: "ALIBABA_TOKEN_PLAN_API_KEY",
    doc: "https://www.alibabacloud.com/help/en/model-studio/token-plan-overview",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "deepseek-v4.1-flash",
      "qwen3.8-flash",
      "glm-5.3",
      "deepseek-v4-pro-0813",
      "qwen3.8-max",
    ],
  },
  {
    id: "alibaba-token-plan-cn",
    name: "Alibaba Token Plan (China)",
    baseURL: "https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
    credentialEnvVar: "ALIBABA_TOKEN_PLAN_CN_API_KEY",
    doc: "https://www.alibabacloud.com/help/zh/model-studio/token-plan-overview",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "deepseek-v4.1-flash",
      "qwen3.8-flash",
      "glm-5.3",
      "deepseek-v4-pro-0813",
      "qwen3.8-max",
    ],
  },
  {
    id: "ambient",
    name: "Ambient",
    baseURL: "https://api.ambient.xyz/v1",
    credentialEnvVar: "AMBIENT_API_KEY",
    doc: "https://ambient.xyz",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "qwen/qwen3.8-27b",
      "deepseek/deepseek-v4-flash-0731",
      "ambient/large",
      "z-ai/glm-5.2",
      "zai-org/GLM-5.2-FP8",
    ],
  },
  {
    id: "amd",
    name: "AMD",
    baseURL: "https://developer.amd.com.cn/radeon/api/v1",
    credentialEnvVar: "AMD_API_KEY",
    doc: "https://developer.amd.com.cn/radeon/tokenfactory",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "DeepSeek-V4.1-Flash",
      "MiniCPM5-2B",
      "Qwen3.8-Flash-Next",
      "DeepSeek-V4-Flash-Vision-Exp",
      "Qwen3.8-27B",
    ],
  },
  {
    id: "anyapi",
    name: "AnyAPI",
    baseURL: "https://api.anyapi.ai/v1",
    credentialEnvVar: "ANYAPI_API_KEY",
    doc: "https://docs.anyapi.ai",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "deepseek/deepseek-v4-flash",
      "deepseek/deepseek-v4-pro",
      "xai/grok-4.3",
      "anthropic/claude-opus-4-7",
      "openai/gpt-5.4",
    ],
  },
  {
    id: "arcee",
    name: "Arcee",
    baseURL: "https://api.arcee.ai/api/v1",
    credentialEnvVar: "ARCEE_API_KEY",
    doc: "https://docs.arcee.ai",
    capabilities: ["reasoning", "toolCalling", "structuredOutput"],
    knownModels: [
      "deepseek/deepseek-v4-pro-0813",
      "deepseek/deepseek-v4-flash-latest",
      "thinkingmachines/inkling-small",
      "moonshotai/kimi-k3",
      "zai-org/glm-5.2",
    ],
  },
  {
    id: "auriko",
    name: "Auriko",
    baseURL: "https://api.auriko.ai/v1",
    credentialEnvVar: "AURIKO_API_KEY",
    doc: "https://docs.auriko.ai",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "deepseek-v4-flash",
      "deepseek-v4-pro",
      "kimi-k2.6",
      "grok-4.3",
      "claude-opus-4-7",
    ],
  },
  {
    id: "bailing",
    name: "Bailing",
    baseURL: "https://api.tbox.cn/api/llm/v1",
    credentialEnvVar: "BAILING_API_TOKEN",
    doc: "https://alipaytbox.yuque.com/sxs0ba/ling/intro",
    capabilities: ["reasoning", "toolCalling"],
    knownModels: [
      "Ling-1T",
      "Ring-1T",
    ],
  },
  {
    id: "baseten",
    name: "Baseten",
    baseURL: "https://inference.baseten.co/v1",
    credentialEnvVar: "BASETEN_API_KEY",
    doc: "https://docs.baseten.co/inference/model-apis/overview",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "deepseek-ai/DeepSeek-V4.1-Flash",
      "deepseek-ai/DeepSeek-V4.1-Flash-Fast",
      "zai-org/GLM-5.3-Flash",
      "zai-org/GLM-5.3",
      "zai-org/GLM-5.3-Fast",
    ],
  },
  {
    id: "bee",
    name: "Bee by HEOSSI",
    baseURL: "https://api.bee.heossi.com/bee",
    credentialEnvVar: "BEE_API_KEY",
    doc: "https://bee.heossi.com/docs/sdks",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "bee-brood",
      "bee-buzz",
      "bee-cell",
      "bee-comb",
      "bee-hive",
    ],
  },
  {
    id: "berget",
    name: "Berget.AI",
    baseURL: "https://api.berget.ai/v1",
    credentialEnvVar: "BERGET_API_KEY",
    doc: "https://api.berget.ai",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "zai-org/GLM-5.3-Flash",
      "Qwen/Qwen3.8-27B-FP8",
      "moonshotai/Kimi-K3",
      "zai-org/GLM-5.2",
      "google/gemma-4-31B-it",
    ],
  },
  {
    id: "blueclaw",
    name: "Blue Claw",
    baseURL: "https://openai.blueclaw.network/v1",
    credentialEnvVar: "BLUECLAW_API_KEY",
    doc: "https://blueclaw.network",
    capabilities: ["reasoning", "toolCalling", "structuredOutput"],
    knownModels: [
      "Qwen3.8-27B",
    ],
  },
  {
    id: "bothub",
    name: "Bothub",
    baseURL: "https://openai.bothub.ru/v1",
    credentialEnvVar: "BOTHUB_API_KEY",
    doc: "https://bothub.ru/models",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "muse-spark-1.3-contributor",
      "glm-5.3-flash",
      "glm-5.3",
      "deepseek-v4-pro-0813",
      "deepseek-v4-flash-0731",
    ],
  },
  {
    id: "hyper",
    name: "Charm Hyper",
    baseURL: "https://hyper.charm.land/v1",
    credentialEnvVar: "HYPER_API_KEY",
    doc: "https://hyper.charm.land",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "deepseek-v4.1-flash",
      "kimi-k2-thinking",
      "glm-5.3",
      "glm-5.3-flash",
      "qwen3.8-2.4t-a95b",
    ],
  },
  {
    id: "chutes",
    name: "Chutes",
    baseURL: "https://llm.chutes.ai/v1",
    credentialEnvVar: "CHUTES_API_KEY",
    doc: "https://llm.chutes.ai/v1/models",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "Qwen/Qwen3.8-27B-TEE",
      "deepseek-ai/DeepSeek-V4-Flash-0731-TEE",
      "moonshotai/Kimi-K3-TEE",
      "Nemotron-3-Nano-Omni-30B-TEE",
      "zai-org/GLM-5.2-TEE",
    ],
  },
  {
    id: "clarifai",
    name: "Clarifai",
    baseURL: "https://api.clarifai.com/v2/ext/openai/v1",
    credentialEnvVar: "CLARIFAI_PAT",
    doc: "https://docs.clarifai.com/compute/inference/",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "moonshotai/chat-completion/models/Kimi-K2_6",
      "minimaxai/chat-completion/models/MiniMax-M2_5-high-throughput",
      "arcee_ai/AFM/models/trinity-mini",
      "mistralai/completion/models/Ministral-3-14B-Reasoning-2512",
      "mistralai/completion/models/Ministral-3-3B-Reasoning-2512",
    ],
  },
  {
    id: "claudinio",
    name: "Claudinio",
    baseURL: "https://api.claudin.io/v1",
    credentialEnvVar: "CLAUDINIO_API_KEY",
    doc: "https://claudin.io",
    capabilities: ["reasoning", "toolCalling", "imageInput"],
    knownModels: [
      "claudinio",
      "claudius",
    ],
  },
  {
    id: "cline-pass",
    name: "ClinePass",
    baseURL: "https://api.cline.bot/api/v1",
    credentialEnvVar: "CLINE_API_KEY",
    doc: "https://docs.cline.bot/getting-started/clinepass",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "cline-pass/mimo-v2.6-flash",
      "cline-pass/mimo-v2.6-pro",
      "cline-pass/deepseek-v4.1-flash",
      "cline-pass/muse-spark-1.3-contributor",
      "cline-pass/glm-5.3-flash",
    ],
  },
  {
    id: "cloudferro-sherlock",
    name: "CloudFerro Sherlock",
    baseURL: "https://api-sherlock.cloudferro.com/openai/v1/",
    credentialEnvVar: "CLOUDFERRO_SHERLOCK_API_KEY",
    doc: "https://docs.sherlock.cloudferro.com/",
    capabilities: ["reasoning", "toolCalling", "structuredOutput"],
    knownModels: [
      "MiniMaxAI/MiniMax-M2.5",
      "openai/gpt-oss-120b",
      "speakleash/Bielik-11B-v2.6-Instruct",
      "speakleash/Bielik-11B-v3.0-Instruct",
      "meta-llama/Llama-3.3-70B-Instruct",
    ],
  },
  {
    id: "coralbricks",
    name: "CoralBricks",
    baseURL: "https://inference.coralbricks.ai/v1",
    credentialEnvVar: "CORAL_API_KEY",
    doc: "https://www.coralbricks.ai/docs",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "deepseek-v4.1-flash-fast",
      "deepseek-v4.1-flash-fast-fp4",
      "glm-5.3-fast",
      "glm-5.3-fp4",
    ],
  },
  {
    id: "wandb",
    name: "CoreWeave",
    baseURL: "https://api.inference.wandb.ai/v1",
    credentialEnvVar: "WANDB_API_KEY",
    doc: "https://docs.wandb.ai/inference",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "deepseek-ai/DeepSeek-V4.1-Flash",
      "zai-org/GLM-5.3-Flash",
      "ibm-granite/granite-4.2-8b",
      "Qwen/Qwen3.8-27B",
      "deepseek-ai/DeepSeek-V4-Pro-0813",
    ],
  },
  {
    id: "cortecs",
    name: "Cortecs",
    baseURL: "https://api.cortecs.ai/v1",
    credentialEnvVar: "CORTECS_API_KEY",
    doc: "https://api.cortecs.ai/v1/models",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "claude-haiku-5.5",
      "mistral-large-4-0",
      "gpt-6.1-sol",
      "claude-sonnet-5.5",
      "claude-opus-5.5",
    ],
  },
  {
    id: "crof",
    name: "CrofAI",
    baseURL: "https://crof.ai/v1",
    credentialEnvVar: "CROF_API_KEY",
    doc: "https://crof.ai/docs",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "glm-5.3-flash",
      "deepseek-v4-flash-vision-exp",
      "glm-5.3",
      "qwen3.8-27b",
      "deepseek-v4-pro-0813",
    ],
  },
  {
    id: "crossmodel",
    name: "CrossModel",
    baseURL: "https://api.crossmodel.ai/v1",
    credentialEnvVar: "CROSSMODEL_API_KEY",
    doc: "https://www.crossmodel.ai/docs",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "anthropic/claude-haiku-5-5",
      "openai/gpt-6.1-sol",
      "anthropic/claude-sonnet-5-5",
      "anthropic/claude-opus-5-5",
      "openai/gpt-6-luna",
    ],
  },
  {
    id: "crusoe",
    name: "Crusoe",
    baseURL: "https://api.inference.crusoecloud.com/v1",
    credentialEnvVar: "CRUSOE_API_KEY",
    doc: "https://docs.crusoecloud.com/managed-inference/overview",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "zai/GLM-5.2",
      "nvidia/Nemotron-3-Nano-Omni-Reasoning-30B-A3B",
      "moonshotai/Kimi-K2.6",
      "zai/GLM-5.1",
      "google/gemma-4-31b-it",
    ],
  },
  {
    id: "drun",
    name: "D.Run (China)",
    baseURL: "https://chat.d.run/v1",
    credentialEnvVar: "DRUN_API_KEY",
    doc: "https://www.d.run",
    capabilities: ["reasoning", "toolCalling"],
    knownModels: [
      "public/minimax-m25",
      "public/deepseek-r1",
      "public/deepseek-v3",
    ],
  },
  {
    id: "daoxe",
    name: "DaoXE",
    baseURL: "https://daoxe.com/v1",
    credentialEnvVar: "DAOXE_API_KEY",
    doc: "https://daoxe.com/pricing",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "grok-4.5",
      "claude-opus-4-8",
      "gpt-5.5",
      "grok-4.3",
      "gpt-5.4",
    ],
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    baseURL: "https://api.deepseek.com",
    credentialEnvVar: "DEEPSEEK_API_KEY",
    doc: "https://api-docs.deepseek.com/quick_start/pricing",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "deepseek-flash",
      "deepseek-v4-flash",
      "deepseek-v4-flash-vision-exp",
      "deepseek-v4-pro",
    ],
  },
  {
    id: "llmgateway",
    name: "DevPass (LLM Gateway)",
    baseURL: "https://api.llmgateway.io/v1",
    credentialEnvVar: "LLMGATEWAY_API_KEY",
    doc: "https://llmgateway.io/docs",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "claude-haiku-5-5",
      "mistral-large-4",
      "gpt-6.1-sol",
      "ling-3.1-flash",
      "claude-sonnet-5-5",
    ],
  },
  {
    id: "digitalocean",
    name: "DigitalOcean",
    baseURL: "https://inference.do-ai.run/v1",
    credentialEnvVar: "DIGITALOCEAN_ACCESS_TOKEN",
    doc: "https://docs.digitalocean.com/products/gradient-ai-platform/details/models/",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "openai-gpt-6-1-sol",
      "anthropic-claude-sonnet-5.5",
      "anthropic-claude-opus-5.5",
      "openai-gpt-6-luna",
      "openai-gpt-6-sol",
    ],
  },
  {
    id: "dinference",
    name: "DInference",
    baseURL: "https://api.dinference.com/v1",
    credentialEnvVar: "DINFERENCE_API_KEY",
    doc: "https://dinference.com",
    capabilities: ["reasoning", "toolCalling", "structuredOutput"],
    knownModels: [
      "glm-5.2",
      "glm-5.1",
      "glm-5",
      "minimax-m2.5",
      "glm-4.7",
    ],
  },
  {
    id: "ebcloud",
    name: "EBCloud",
    baseURL: "https://maas-api.ebcloud.com/v1",
    credentialEnvVar: "EBCLOUD_API_KEY",
    doc: "https://docs.ebtech.com/ai/model-api.html",
    capabilities: ["reasoning", "toolCalling", "structuredOutput"],
    knownModels: [
      "DeepSeek-V4-Flash",
      "DeepSeek-V4-Pro",
      "Kimi-K2.6",
      "GLM-5.1",
    ],
  },
  {
    id: "echo",
    name: "Echo",
    baseURL: "https://echo.tracerml.ai/v1",
    credentialEnvVar: "ECHO_API_KEY",
    doc: "https://echo.tracerml.ai/docs/api",
    capabilities: ["reasoning", "toolCalling"],
    knownModels: [
      "echo",
    ],
  },
  {
    id: "edenai",
    name: "Eden AI",
    baseURL: "https://api.edenai.run/v3",
    credentialEnvVar: "EDENAI_API_KEY",
    doc: "https://docs.edenai.co",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "anthropic/claude-haiku-5-5",
      "google/gemini-nano-banana-2.1",
      "vertex/gemini-nano-banana-2.1",
      "openai/gpt-6.1-sol",
      "anthropic/claude-sonnet-5-5",
    ],
  },
  {
    id: "empiriolabs",
    name: "EmpirioLabs AI",
    baseURL: "https://api.empiriolabs.ai/v1",
    credentialEnvVar: "EMPIRIOLABS_API_KEY",
    doc: "https://docs.empiriolabs.ai",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "mimo-v2-6-flash",
      "mimo-v2-6-pro",
      "mimo-v2-6-pro-ultraspeed",
      "qwen3-8-omni-flash",
      "step-5-preview",
    ],
  },
  {
    id: "engy",
    name: "engy",
    baseURL: "https://api.engy.ai/v1",
    credentialEnvVar: "ENGY_API_KEY",
    doc: "https://engy.ai/pricing",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "deepseek-v4.1-flash",
      "glm-5.3-flash",
      "glm-5.3",
      "qwen3.8-27b",
      "deepseek-v4-flash-0731",
    ],
  },
  {
    id: "evroc",
    name: "evroc",
    baseURL: "https://models.think.evroc.com/v1",
    credentialEnvVar: "EVROC_API_KEY",
    doc: "https://docs.evroc.com/products/think/overview.html",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "Qwen/Qwen3.8-27B",
      "zai-org/GLM-5.2",
      "evroc/roc",
      "mistralai/Mistral-Medium-3.5-128B",
      "moonshotai/Kimi-K2.6",
    ],
  },
  {
    id: "fastrouter",
    name: "FastRouter",
    baseURL: "https://go.fastrouter.ai/api/v1",
    credentialEnvVar: "FASTROUTER_API_KEY",
    doc: "https://fastrouter.ai/models",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "anthropic/claude-opus-4.8",
      "google/gemini-3.5-flash",
      "deepseek/deepseek-v4-pro",
      "openai/gpt-5.5",
      "openai/gpt-5.5-pro",
    ],
  },
  {
    id: "fireworks-ai",
    name: "Fireworks AI",
    baseURL: "https://api.fireworks.ai/inference/v1/",
    credentialEnvVar: "FIREWORKS_API_KEY",
    doc: "https://fireworks.ai/docs/",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "accounts/fireworks/models/ember-1",
      "accounts/fireworks/models/deepseek-v4p1-flash",
      "accounts/fireworks/routers/deepseek-flash-latest",
      "accounts/fireworks/routers/glm-5p3-fast",
      "accounts/fireworks/routers/glm-fast-latest",
    ],
  },
  {
    id: "friendli",
    name: "Friendli",
    baseURL: "https://api.friendli.ai/serverless/v1",
    credentialEnvVar: "FRIENDLI_TOKEN",
    doc: "https://friendli.ai/docs/guides/serverless_endpoints/introduction",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "zai-org/GLM-5.3-Flash",
      "zai-org/GLM-5.3",
      "zai-org/GLM-5.2",
      "zai-org/GLM-5.1",
      "google/gemma-4-31B-it",
    ],
  },
  {
    id: "frogbot",
    name: "FrogBot",
    baseURL: "https://app.frogbot.ai/api/v1",
    credentialEnvVar: "FROGBOT_API_KEY",
    doc: "https://docs.frogbot.ai",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "grok-4-3",
      "deepseek-v4-pro",
      "claude-opus-4-7",
      "qwen-3-6-plus",
      "minimax-m2-7",
    ],
  },
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    baseURL: "https://api.githubcopilot.com",
    credentialEnvVar: "GITHUB_TOKEN",
    doc: "https://docs.github.com/en/copilot",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "claude-haiku-5.5",
      "gpt-6.1-sol",
      "claude-sonnet-5.5",
      "claude-opus-5.5",
      "gpt-6-luna",
    ],
  },
  {
    id: "gmicloud",
    name: "GMI Cloud",
    baseURL: "https://api.gmi-serving.com/v1",
    credentialEnvVar: "GMICLOUD_API_KEY",
    doc: "https://docs.gmicloud.ai/inference-engine/api-reference/llm-api-reference",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "Qwen/Qwen3.8-Flash",
      "Qwen/Qwen3.8-Max",
      "zai-org/GLM-5.2-FP8",
      "moonshotai/kimi-k2.7-code-highspeed",
      "MiniMaxAI/MiniMax-M3",
    ],
  },
  {
    id: "google",
    name: "Google Gemini",
    baseURL: "https://generativelanguage.googleapis.com/v1beta/openai",
    credentialEnvVar: "GOOGLE_API_KEY",
    doc: "https://ai.google.dev/gemini-api/docs/models",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "gemini-3-pro-preview",
      "gemini-3-flash-preview",
      "gemini-2.5-pro",
    ],
    handAdded: true, // models.dev lists three aliases for this Credential (GOOGLE_API_KEY, GOOGLE_GENERATIVE_AI_API_KEY, GEMINI_API_KEY). The first is used here.
  },
  {
    id: "greenpt",
    name: "GreenPT",
    baseURL: "https://api.greenpt.ai/v1",
    credentialEnvVar: "GREENPT_API_KEY",
    doc: "https://docs.greenpt.ai",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "deepseek-v4.1-flash",
      "glm-5.3-flash",
      "glm-5.3",
      "deepseek-v4-flash-0731",
      "kimi-k3",
    ],
  },
  {
    id: "groq",
    name: "Groq",
    baseURL: "https://api.groq.com/openai/v1",
    credentialEnvVar: "GROQ_API_KEY",
    doc: "https://console.groq.com/docs/models",
    capabilities: ["toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "qwen/qwen3.8-27b",
      "llama-3.3-70b-versatile",
      "openai/gpt-oss-120b",
    ],
    handAdded: true, // models.dev carries no base URL for Groq; this is its documented OpenAI-compatible one.
  },
  {
    id: "helicone",
    name: "Helicone",
    baseURL: "https://ai-gateway.helicone.ai/v1",
    credentialEnvVar: "HELICONE_API_KEY",
    doc: "https://helicone.ai/models",
    capabilities: ["reasoning", "toolCalling"],
    knownModels: [
      "claude-4.5-opus",
      "gemini-3-pro-preview",
      "grok-4-1-fast-non-reasoning",
      "grok-4-1-fast-reasoning",
      "kimi-k2-thinking",
    ],
  },
  {
    id: "hetzner",
    name: "Hetzner",
    baseURL: "https://inference.hetzner.com/api/v1",
    credentialEnvVar: "HETZNER_API_KEY",
    doc: "https://experiments.hetzner.com/docs/inference",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "Qwen3.8-27B",
      "Qwen/Qwen3.6-35B-A3B-FP8",
    ],
  },
  {
    id: "hpc-ai",
    name: "HPC-AI",
    baseURL: "https://api.hpc-ai.com/inference/v1",
    credentialEnvVar: "HPC_AI_API_KEY",
    doc: "https://www.hpc-ai.com/doc/docs/quickstart/",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "zai-org/glm-5.2",
      "moonshotai/kimi-k2.7-code",
      "deepseek/deepseek-v4-flash",
      "deepseek/deepseek-v4-pro",
      "openai/gpt-5.5",
    ],
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    baseURL: "https://router.huggingface.co/v1",
    credentialEnvVar: "HF_TOKEN",
    doc: "https://huggingface.co/docs/inference-providers",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "deepseek-ai/DeepSeek-V4.1-Flash",
      "tencent/Hy4-preview",
      "zai-org/GLM-5.3-Flash",
      "deepseek-ai/DeepSeek-V4-Flash-Vision-Exp",
      "Qwen/Qwen3.8-27B",
    ],
  },
  {
    id: "iflowcn",
    name: "iFlow",
    baseURL: "https://apis.iflow.cn/v1",
    credentialEnvVar: "IFLOW_API_KEY",
    doc: "https://platform.iflow.cn/en/docs",
    capabilities: ["reasoning", "toolCalling", "imageInput"],
    knownModels: [
      "kimi-k2-0905",
      "qwen3-235b-a22b-instruct",
      "qwen3-235b-a22b-thinking-2507",
      "qwen3-coder-plus",
      "deepseek-r1",
    ],
  },
  {
    id: "impossibl",
    name: "Impossibl",
    baseURL: "https://api.impossibl.com/v1",
    credentialEnvVar: "IMPOSSIBL_API_KEY",
    doc: "https://impossibl.com/docs/models",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "google/gemini-3.5-flash-lite",
      "google/gemini-3.6-flash",
      "qwen/qwen3.8-max-preview",
      "moonshotai/kimi-k3",
      "thinkingmachines/inkling",
    ],
  },
  {
    id: "inception",
    name: "Inception",
    baseURL: "https://api.inceptionlabs.ai/v1/",
    credentialEnvVar: "INCEPTION_API_KEY",
    doc: "https://docs.inceptionlabs.ai/get-started/models",
    capabilities: ["reasoning", "toolCalling", "structuredOutput"],
    knownModels: [
      "mercury-2.5",
      "mercury-edit-2",
      "mercury-2",
    ],
  },
  {
    id: "inceptron",
    name: "Inceptron",
    baseURL: "https://api.inceptron.io/v1",
    credentialEnvVar: "INCEPTRON_API_KEY",
    doc: "https://docs.inceptron.io",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "deepseek-ai/DeepSeek-V4-Flash-0731",
      "zai-org/GLM-5.2",
      "moonshotai/Kimi-K2.7-Code",
      "moonshotai/Kimi-K2.6",
    ],
  },
  {
    id: "inco",
    name: "Inco",
    baseURL: "https://api.inco.ai/v1",
    credentialEnvVar: "INCO_API_KEY",
    doc: "https://platform.inco.ai/docs",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "deepseek-v4.1-flash:fast",
      "glm-5.3-flash:fast",
      "glm-5.3",
      "glm-5.3:fast",
      "kimi-k3:fast",
    ],
  },
  {
    id: "infer",
    name: "Infer by Flow7",
    baseURL: "https://infer.flow7.org/v1",
    credentialEnvVar: "INFER_API_KEY",
    doc: "https://infer.flow7.org/opencode",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "infer/gpt-6-astra:official",
      "infer/gpt-5.6-sol:official",
    ],
  },
  {
    id: "inference",
    name: "Inference",
    baseURL: "https://inference.net/v1",
    credentialEnvVar: "INFERENCE_API_KEY",
    doc: "https://inference.net/models",
    capabilities: ["toolCalling", "imageInput"],
    knownModels: [
      "google/gemma-3",
      "meta/llama-3.1-8b-instruct",
      "meta/llama-3.2-11b-vision-instruct",
      "meta/llama-3.2-1b-instruct",
      "meta/llama-3.2-3b-instruct",
    ],
  },
  {
    id: "inferx",
    name: "InferX",
    baseURL: "https://model.inferx.net/endpoints/v1",
    credentialEnvVar: "INFERX_API_KEY",
    doc: "https://model.inferx.net/endpoints",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "Agents-A1",
      "Ornith-1.0-35B-FP8",
      "deepseek-v4-flash",
      "mimo-v25",
      "Qwen3.6-27B-FP8",
    ],
  },
  {
    id: "io-net",
    name: "IO.NET",
    baseURL: "https://api.intelligence.io.solutions/api/v1",
    credentialEnvVar: "IOINTELLIGENCE_API_KEY",
    doc: "https://io.net/docs/guides/intelligence/io-intelligence",
    capabilities: ["reasoning", "toolCalling"],
    knownModels: [
      "Qwen/Qwen3-235B-A22B-Thinking-2507",
      "mistralai/Magistral-Small-2506",
      "mistralai/Devstral-Small-2505",
      "deepseek-ai/DeepSeek-R1-0528",
      "Intel/Qwen3-Coder-480B-A35B-Instruct-int4-mixed-ar",
    ],
  },
  {
    id: "iteracompute",
    name: "IteraCompute",
    baseURL: "https://api.iteracompute.com/v1",
    credentialEnvVar: "ITERACOMPUTE_API_KEY",
    doc: "https://iteracompute.com/docs.html",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "z-ai/glm-5.3-flash",
      "ornith-ai/ornith-1.5-35b-a3b",
      "qwen/qwen3.8-27b",
      "z-ai/glm-5.3",
      "deepseek/deepseek-v4-pro-0813",
    ],
  },
  {
    id: "jalapeno",
    name: "Jalapeno Cloud",
    baseURL: "https://api.jalapeno-cloud.ai/v1",
    credentialEnvVar: "JALAPENO_API_KEY",
    doc: "https://www.jalapeno-cloud.ai/docs/",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "Kimi-K3",
      "Hy3",
      "GLM-5.2",
      "Kimi-K2.7-Code",
      "MiniMax-M3",
    ],
  },
  {
    id: "jiekou",
    name: "Jiekou.AI",
    baseURL: "https://api.jiekou.ai/openai",
    credentialEnvVar: "JIEKOU_API_KEY",
    doc: "https://docs.jiekou.ai/docs/support/quickstart?utm_source=github_models.dev",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "claude-opus-4-6",
      "gpt-5.1",
      "qwen/qwen3-coder-next",
      "baidu/ernie-4.5-300b-a47b-paddle",
      "baidu/ernie-4.5-vl-424b-a47b",
    ],
  },
  {
    id: "kenari",
    name: "Kenari",
    baseURL: "https://kenari.id/v1",
    credentialEnvVar: "KENARI_API_KEY",
    doc: "https://kenari.id/docs",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "deepseek-v4-1-flash",
      "glm-5-3-flash",
      "glm-5-3",
      "gemini-3-7-flash",
      "grok-4-6",
    ],
  },
  {
    id: "kilo",
    name: "Kilo Gateway",
    baseURL: "https://api.kilo.ai/api/gateway",
    credentialEnvVar: "KILO_API_KEY",
    doc: "https://kilo.ai",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "anthropic/claude-haiku-5.5",
      "google/gemini-nano-banana-2.1",
      "mistralai/mistral-large-4-0",
      "inclusionai/ling-3.1-flash",
      "unbiased/pareto-26.10-preview",
    ],
  },
  {
    id: "kimi-code-plan-global",
    name: "Kimi For Coding (kimi.ai)",
    baseURL: "https://api.kimi.ai/coding/v1",
    credentialEnvVar: "KIMI_API_KEY",
    doc: "https://www.kimi.ai/code/docs/en/kimi-code/models.html",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "kimi-for-coding",
      "k3",
      "k3-256k",
      "kimi-for-coding-highspeed",
    ],
  },
  {
    id: "kimi-code-plan-cn",
    name: "Kimi For Coding (kimi.com)",
    baseURL: "https://api.kimi.com/coding/v1",
    credentialEnvVar: "KIMI_CN_API_KEY",
    doc: "https://www.kimi.com/code/docs/en/kimi-code/models.html",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "kimi-for-coding",
      "k3",
      "k3-256k",
      "kimi-for-coding-highspeed",
    ],
  },
  {
    id: "klokintegration",
    name: "klokintegration.se",
    baseURL: "https://api-gw.klok.ipaas.se/proxy/kloker-key/v1",
    credentialEnvVar: "KLOKINTEGRATION_API_KEY",
    doc: "https://klokintegration.se/docs/ai-api",
    capabilities: ["toolCalling"],
    knownModels: [
      "Kloker",
      "Kloker-Integration-Architect",
      "Kloker-Integration-Developer",
    ],
  },
  {
    id: "kosmik",
    name: "Kosmik Compute",
    baseURL: "https://api.koscompute.com/v1",
    credentialEnvVar: "KOSMIK_API_KEY",
    doc: "https://api.koscompute.com/docs/",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "qwen/qwen3.8-27b",
    ],
  },
  {
    id: "kuae-cloud-coding-plan",
    name: "KUAE Cloud Coding Plan",
    baseURL: "https://coding-plan-endpoint.kuaecloud.net/v1",
    credentialEnvVar: "KUAE_API_KEY",
    doc: "https://docs.mthreads.com/kuaecloud/kuaecloud-doc-online/coding_plan/",
    capabilities: ["reasoning", "toolCalling"],
    knownModels: [
      "GLM-4.7",
    ],
  },
  {
    id: "lilac",
    name: "Lilac",
    baseURL: "https://api.getlilac.com/v1",
    credentialEnvVar: "LILAC_API_KEY",
    doc: "https://docs.getlilac.com/inference/models",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "zai-org/glm-5.2",
      "minimaxai/minimax-m3",
      "moonshotai/kimi-k2.6",
      "google/gemma-4-31b-it",
    ],
  },
  {
    id: "llama",
    name: "Llama",
    baseURL: "https://api.llama.com/compat/v1/",
    credentialEnvVar: "LLAMA_API_KEY",
    doc: "https://llama.developer.meta.com/docs/models",
    capabilities: ["toolCalling", "imageInput"],
    knownModels: [
      "cerebras-llama-4-maverick-17b-128e-instruct",
      "cerebras-llama-4-scout-17b-16e-instruct",
      "groq-llama-4-maverick-17b-128e-instruct",
      "llama-4-maverick-17b-128e-instruct-fp8",
      "llama-4-scout-17b-16e-instruct-fp8",
    ],
  },
  {
    id: "llmgateway-providers",
    name: "LLM Gateway",
    baseURL: "https://api.llmgateway.io/v1",
    credentialEnvVar: "LLMGATEWAY_API_KEY",
    doc: "https://llmgateway.io/docs",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "anthropic/claude-haiku-5-5",
      "aws-bedrock/claude-haiku-5-5",
      "mistral/mistral-large-4",
      "azure/gpt-6.1-sol",
      "novita/ling-3.1-flash",
    ],
  },
  {
    id: "llmtech",
    name: "LLM Tech",
    baseURL: "https://api.llmtech.eu/v1",
    credentialEnvVar: "LLMTECH_API_KEY",
    doc: "https://llmtech.eu/models/qwen3.8-27b",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "nvidia/Qwen3.8-27B-NVFP4",
    ],
  },
  {
    id: "llmtr",
    name: "LLMTR",
    baseURL: "https://llmtr.com/v1",
    credentialEnvVar: "LLMTR_API_KEY",
    doc: "https://llmtr.com/docs",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "muse-glimmer-30b-tr",
      "upstage/solar-pro4",
      "meta/muse-spark-1.2-contributor",
      "thinkingmachines/inkling-small",
      "thinkingmachines/inkling",
    ],
  },
  {
    id: "longcat",
    name: "LongCat",
    baseURL: "https://api.longcat.chat/openai",
    credentialEnvVar: "LONGCAT_API_KEY",
    doc: "https://longcat.chat/platform/docs/",
    capabilities: ["reasoning", "toolCalling"],
    knownModels: [
      "LongCat-2.0",
    ],
  },
  {
    id: "lucidquery",
    name: "LucidQuery",
    baseURL: "https://api.lucidquery.com/v1",
    credentialEnvVar: "LUCIDQUERY_API_KEY",
    doc: "https://lucidquery.com/docs",
    capabilities: ["reasoning", "toolCalling", "imageInput"],
    knownModels: [
      "lucidquery-agi-01-frontier",
      "lucidquery-agi-01-swift",
      "lucidquery-nexus-coder",
      "lucidnova-rf1-100b",
    ],
  },
  {
    id: "meganova",
    name: "Meganova",
    baseURL: "https://api.meganova.ai/v1",
    credentialEnvVar: "MEGANOVA_API_KEY",
    doc: "https://docs.meganova.ai",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "MiniMaxAI/MiniMax-M2.5",
      "zai-org/GLM-5",
      "Qwen/Qwen3.5-Plus",
      "moonshotai/Kimi-K2.5",
      "MiniMaxAI/MiniMax-M2.1",
    ],
  },
  {
    id: "melious",
    name: "Melious",
    baseURL: "https://api.melious.ai/v1",
    credentialEnvVar: "MELIOUS_API_KEY",
    doc: "https://melious.ai/docs/reference/models",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "deepseek-v4.1-flash",
      "glm-5.3-flash",
      "glm-5.3",
      "deepseek-v4-flash-0731",
      "kimi-k3",
    ],
  },
  {
    id: "meta",
    name: "Meta",
    baseURL: "https://api.meta.ai/v1",
    credentialEnvVar: "META_MODEL_API_KEY",
    doc: "https://dev.meta.ai/docs",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "muse-spark-1.3",
      "muse-spark-1.3-contributor",
      "muse-spark-1.2",
      "muse-spark-1.2-contributor",
      "muse-spark-1.1",
    ],
  },
  {
    id: "mistral",
    name: "Mistral",
    baseURL: "https://api.mistral.ai/v1",
    credentialEnvVar: "MISTRAL_API_KEY",
    doc: "https://docs.mistral.ai/getting-started/models/",
    capabilities: ["toolCalling", "structuredOutput"],
    knownModels: [
      "mistral-large-4-0",
      "mistral-medium-3.1",
      "magistral-medium-3.1",
    ],
    handAdded: true, // models.dev carries no base URL for Mistral; this is its documented OpenAI-compatible one.
  },
  {
    id: "mixlayer",
    name: "Mixlayer",
    baseURL: "https://models.mixlayer.ai/v1",
    credentialEnvVar: "MIXLAYER_API_KEY",
    doc: "https://docs.mixlayer.com",
    capabilities: ["reasoning", "toolCalling"],
    knownModels: [
      "qwen/qwen3.5-122b-a10b",
      "qwen/qwen3.5-27b",
      "qwen/qwen3.5-35b-a3b",
      "qwen/qwen3.5-397b-a17b",
      "qwen/qwen3.5-9b",
    ],
  },
  {
    id: "moark",
    name: "Moark",
    baseURL: "https://moark.com/v1",
    credentialEnvVar: "MOARK_API_KEY",
    doc: "https://moark.com/docs/openapi/v1#tag/%E6%96%87%E6%9C%AC%E7%94%9F%E6%88%90",
    capabilities: ["reasoning", "toolCalling"],
    knownModels: [
      "MiniMax-M2.1",
      "GLM-4.7",
    ],
  },
  {
    id: "modal",
    name: "Modal",
    baseURL: "https://inference.us-west.modal.direct/v1",
    credentialEnvVar: "MODAL_PROXY_TOKEN",
    doc: "https://modal.com/docs/guide/endpoints",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "zai-org/GLM-5.3-Flash",
      "Qwen/Qwen3.8-2.4T-A95B",
      "moonshotai/Kimi-K3",
      "thinkingmachines/Inkling-NVFP4",
    ],
  },
  {
    id: "model-oracle-ai",
    name: "Model Oracle AI",
    baseURL: "https://api.modeloracle.com/api/v1",
    credentialEnvVar: "MODEL_ORACLE_API_KEY",
    doc: "https://modeloracle.com/setup/",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "claude-sonnet-5",
      "auto",
      "glm-5.2",
      "claude-fable-5",
      "claude-opus-4.8",
    ],
  },
  {
    id: "modelis",
    name: "Modelis",
    baseURL: "https://modelishub.com/v1",
    credentialEnvVar: "MODELIS_API_KEY",
    doc: "https://modelishub.com/pricing",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "claude-fable-5",
      "qwen/qwen3.7-plus",
      "claude-opus-4-8",
      "qwen/qwen3.7-max",
      "deepseek-v4-flash",
    ],
  },
  {
    id: "modelscope",
    name: "ModelScope",
    baseURL: "https://api-inference.modelscope.cn/v1",
    credentialEnvVar: "MODELSCOPE_API_KEY",
    doc: "https://modelscope.cn/docs/model-service/API-Inference/intro",
    capabilities: ["reasoning", "toolCalling"],
    knownModels: [
      "ZhipuAI/GLM-4.6",
      "Qwen/Qwen3-Coder-30B-A3B-Instruct",
      "Qwen/Qwen3-30B-A3B-Instruct-2507",
      "Qwen/Qwen3-30B-A3B-Thinking-2507",
      "ZhipuAI/GLM-4.5",
    ],
  },
  {
    id: "moonshotai",
    name: "Moonshot AI",
    baseURL: "https://api.moonshot.ai/v1",
    credentialEnvVar: "MOONSHOT_API_KEY",
    doc: "https://platform.moonshot.ai/docs/api/chat",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "kimi-k3",
      "kimi-k2.7-code",
      "kimi-k2.7-code-highspeed",
      "kimi-k2.6",
    ],
  },
  {
    id: "moonshotai-cn",
    name: "Moonshot AI (China)",
    baseURL: "https://api.moonshot.cn/v1",
    credentialEnvVar: "MOONSHOT_CN_API_KEY",
    doc: "https://platform.moonshot.cn/docs/api/chat",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "kimi-k3",
      "kimi-k2.7-code",
      "kimi-k2.7-code-highspeed",
      "kimi-k2.6",
    ],
  },
  {
    id: "morph",
    name: "Morph",
    baseURL: "https://api.morphllm.com/v1",
    credentialEnvVar: "MORPH_API_KEY",
    doc: "https://docs.morphllm.com/api-reference/introduction",
    capabilities: [],
    knownModels: [
      "morph-v3-fast",
      "morph-v3-large",
      "auto",
    ],
  },
  {
    id: "nan",
    name: "NaN",
    baseURL: "https://api.nan.builders/v1",
    credentialEnvVar: "NAN_API_KEY",
    doc: "https://nan.builders/docs/models",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "mimo-v2.6-flash",
      "deepseek-v4-flash",
      "glm5.3-flash",
      "qwen3.8-flash",
      "glm5.3",
    ],
  },
  {
    id: "nano-gpt",
    name: "NanoGPT",
    baseURL: "https://nano-gpt.com/api/v1",
    credentialEnvVar: "NANO_GPT_API_KEY",
    doc: "https://docs.nano-gpt.com",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "gemma-4-26b-a4b-it-chimeraxheretic",
      "gemma-4-31b-it-scarlet",
      "anthropic/claude-haiku-5.5",
      "mistralai/mistral-large-4",
      "qwen/qwen3.8-27b-antislop",
    ],
  },
  {
    id: "nearai",
    name: "NEAR AI Cloud",
    baseURL: "https://cloud-api.near.ai/v1",
    credentialEnvVar: "NEARAI_API_KEY",
    doc: "https://docs.near.ai/",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "google/gemini-3.5-flash",
      "google/gemini-3.1-flash-lite",
      "openai/gpt-5.5",
      "Qwen/Qwen3.6-35B-A3B-FP8",
      "anthropic/claude-opus-4-7",
    ],
  },
  {
    id: "nebius",
    name: "Nebius Token Factory",
    baseURL: "https://api.tokenfactory.nebius.com/v1",
    credentialEnvVar: "NEBIUS_API_KEY",
    doc: "https://docs.tokenfactory.nebius.com/",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "deepseek-ai/DeepSeek-V4.1-Flash",
      "zai-org/GLM-5.3-Flash",
      "Qwen/Qwen3.8-27B",
      "zai-org/GLM-5.3",
      "deepseek-ai/DeepSeek-V4-Pro-0813",
    ],
  },
  {
    id: "neosmith",
    name: "NeoSmith",
    baseURL: "https://router.neosmith.ai/v1",
    credentialEnvVar: "NEOSMITH_API_KEY",
    doc: "https://neosmith.ai/docs",
    capabilities: ["reasoning", "toolCalling", "imageInput"],
    knownModels: [
      "neosmith.intelligent-maestro",
      "neosmith.neolite",
      "neosmith.intelligent-basic",
      "neosmith.intelligent-pro",
    ],
  },
  {
    id: "neuralwatt",
    name: "Neuralwatt",
    baseURL: "https://api.neuralwatt.com/v1",
    credentialEnvVar: "NEURALWATT_API_KEY",
    doc: "https://portal.neuralwatt.com/docs",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "mimo-v2.6-pro",
      "mimo-v2.6-pro-flex",
      "deepseek-v4.1-flash",
      "deepseek-v4.1-flash-flex",
      "glm-5.3-flash",
    ],
  },
  {
    id: "nova",
    name: "Nova",
    baseURL: "https://api.nova.amazon.com/v1",
    credentialEnvVar: "NOVA_API_KEY",
    doc: "https://nova.amazon.com/dev/documentation",
    capabilities: ["reasoning", "toolCalling", "imageInput"],
    knownModels: [
      "nova-2-pro-v1",
      "nova-2-lite-v1",
    ],
  },
  {
    id: "novita-ai",
    name: "NovitaAI",
    baseURL: "https://api.novita.ai/openai",
    credentialEnvVar: "NOVITA_API_KEY",
    doc: "https://novita.ai/docs/guides/introduction",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "moonshotai/kimi-k3",
      "zai-org/glm-5.2",
      "moonshotai/kimi-k2.7-code",
      "qwen/qwen3.7-max",
      "inclusionai/ring-2.6-1t",
    ],
  },
  {
    id: "nvidia",
    name: "Nvidia",
    baseURL: "https://integrate.api.nvidia.com/v1",
    credentialEnvVar: "NVIDIA_API_KEY",
    doc: "https://docs.api.nvidia.com/nim/",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "deepseek-ai/deepseek-v4.1-flash",
      "z-ai/glm-5.3-flash",
      "z-ai/glm-5.3",
      "deepseek-ai/deepseek-v4-pro-0813",
      "nvidia/nemotron-3.5-lightning-30b-a3b",
    ],
  },
  {
    id: "oci",
    name: "OCI Generative AI",
    baseURL: "https://inference.generativeai.us-chicago-1.oci.oraclecloud.com/openai/v1",
    credentialEnvVar: "OCI_GENAI_API_KEY",
    doc: "https://docs.oracle.com/en-us/iaas/Content/generative-ai/pretrained-models.htm",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "xai.grok-4.6",
      "xai.grok-4.3",
      "xai.grok-4.20-non-reasoning",
      "xai.grok-4.20-reasoning",
      "openai.gpt-oss-120b",
    ],
  },
  {
    id: "ofox",
    name: "Ofox",
    baseURL: "https://api.ofox.ai/v1",
    credentialEnvVar: "OFOX_API_KEY",
    doc: "https://ofox.ai/docs",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "openai/gpt-6.1-sol",
      "anthropic/claude-sonnet-5.5",
      "anthropic/claude-opus-5.5",
      "openai/gpt-6-luna",
      "openai/gpt-6-sol",
    ],
  },
  {
    id: "ollama-cloud",
    name: "Ollama Cloud",
    baseURL: "https://ollama.com/v1",
    credentialEnvVar: "OLLAMA_API_KEY",
    doc: "https://docs.ollama.com/cloud",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "mistral-large-4",
      "deepseek-v4.1-flash",
      "glm-5.3-flash",
      "glm-5.3",
      "deepseek-v4-pro:0813",
    ],
  },
  {
    id: "openai",
    name: "OpenAI",
    baseURL: "https://api.openai.com/v1",
    credentialEnvVar: "OPENAI_API_KEY",
    doc: "https://platform.openai.com/docs/models",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "gpt-5.4",
      "gpt-5.4-mini",
      "gpt-5.4-nano",
    ],
    handAdded: true, // models.dev carries no base URL for OpenAI; this is the documented one.
  },
  {
    id: "opencode-go",
    name: "OpenCode Go",
    baseURL: "https://opencode.ai/zen/go/v1",
    credentialEnvVar: "OPENCODE_API_KEY",
    doc: "https://opencode.ai/docs/go",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "claude-haiku-5-5",
      "longcat-2.5-preview-free",
      "space-bunny",
      "space-bunny-free",
      "gpt-6-luna",
    ],
  },
  {
    id: "opencode",
    name: "OpenCode Zen",
    baseURL: "https://opencode.ai/zen/v1",
    credentialEnvVar: "OPENCODE_API_KEY",
    doc: "https://opencode.ai/docs/zen",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "claude-haiku-5-5",
      "exo-free",
      "mistral-large-4",
      "fledge-alpha-free",
      "gpt-6.1-sol",
    ],
  },
  {
    id: "openreason",
    name: "OpenReason",
    baseURL: "https://api.openreason.app/v1",
    credentialEnvVar: "OPENREASON_API_KEY",
    doc: "https://openreason.app/docs",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "deepseek-ai/deepseek-v4-flash-0731",
      "moonshotai/kimi-k2.7-code",
      "openai/gpt-oss-120b",
    ],
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    baseURL: "https://openrouter.ai/api/v1",
    credentialEnvVar: "OPENROUTER_API_KEY",
    doc: "https://openrouter.ai/models",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "anthropic/claude-haiku-5.5",
      "google/gemini-nano-banana-2.1",
      "mistralai/mistral-large-4-0",
      "inclusionai/ling-3.1-flash",
      "apodex/apodex-1.1-mini:free",
    ],
  },
  {
    id: "opper",
    name: "Opper",
    baseURL: "https://api.opper.ai/v3/compat",
    credentialEnvVar: "OPPER_API_KEY",
    doc: "https://opper.ai/models",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "gpt-6-astra",
      "gemini-3.8-flash",
      "muse-spark-1.3",
      "claude-fable-5-1",
      "glm-5.3-flash",
    ],
  },
  {
    id: "orcarouter",
    name: "OrcaRouter",
    baseURL: "https://api.orcarouter.ai/v1",
    credentialEnvVar: "ORCAROUTER_API_KEY",
    doc: "https://docs.orcarouter.ai",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "orcarouter/free",
      "z-ai/glm-5.3-flash",
      "z-ai/glm-5.3-flash-free",
      "deepseek/deepseek-v4-flash-vision-exp",
      "qwen/qwen3.8-27b",
    ],
  },
  {
    id: "ovhcloud",
    name: "OVHcloud AI Endpoints",
    baseURL: "https://oai.endpoints.kepler.ai.cloud.ovh.net/v1",
    credentialEnvVar: "OVHCLOUD_API_KEY",
    doc: "https://www.ovhcloud.com/en/public-cloud/ai-endpoints/catalog//",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "qwen3.8-27b",
      "qwen3.6-27b",
      "qwen3.5-397b-a17b",
      "qwen3.5-9b",
      "qwen3guard-gen-0.6b",
    ],
  },
  {
    id: "pareto",
    name: "Pareto Inference",
    baseURL: "https://api.paretoinference.com/v1",
    credentialEnvVar: "PARETO_API_KEY",
    doc: "https://docs.paretoinference.com/",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "z-ai/glm-5.3-flash",
    ],
  },
  {
    id: "pendra",
    name: "Pendra",
    baseURL: "https://api.pendra.ai/api/v1",
    credentialEnvVar: "PENDRA_API_KEY",
    doc: "https://pendra.ai/docs/integrations/opencode",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "deepseek-v4-flash",
      "qwen3.6:27b",
      "glm-4.7-flash",
      "gpt-oss:120b",
      "qwen3-coder:30b",
    ],
  },
  {
    id: "perplexity-agent",
    name: "Perplexity Agent",
    baseURL: "https://api.perplexity.ai/v1",
    credentialEnvVar: "PERPLEXITY_API_KEY",
    doc: "https://docs.perplexity.ai/docs/agent-api/models",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "xai/grok-4.6",
      "deepseek/deepseek-v4-flash-0731",
      "moonshot-ai/kimi-k3",
      "moonshot-ai/kimi-k2.7-code",
      "openai/gpt-5.5",
    ],
  },
  {
    id: "pioneer",
    name: "Pioneer",
    baseURL: "https://api.fastino.ai/v1",
    credentialEnvVar: "PIONEER_API_KEY",
    doc: "https://agent.pioneer.ai/llms.txt",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "fastino/GLiNER-2.5-Decide",
      "fastino/gliner2.5-base-v1",
      "fastino/gliner2.5-multi-v1",
      "nvidia/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-BF16",
      "thinkingmachines/inkling-small",
    ],
  },
  {
    id: "poe",
    name: "Poe",
    baseURL: "https://api.poe.com/v1",
    credentialEnvVar: "POE_API_KEY",
    doc: "https://creator.poe.com/docs/external-applications/openai-compatible-api",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "anthropic/claude-opus-4.8",
      "google/gemini-3.5-flash",
      "empiriolabs/deepseek-v4-flash-el",
      "empiriolabs/deepseek-v4-pro-el",
      "novita/kimi-k2.6",
    ],
  },
  {
    id: "poolside",
    name: "Poolside",
    baseURL: "https://inference.poolside.ai/v1",
    credentialEnvVar: "POOLSIDE_API_KEY",
    doc: "https://platform.poolside.ai",
    capabilities: ["reasoning", "toolCalling"],
    knownModels: [
      "poolside/laguna-s-2.1",
      "poolside/laguna-xs-2.1",
      "poolside/laguna-m.1",
    ],
  },
  {
    id: "qihang-ai",
    name: "QiHang",
    baseURL: "https://api.qhaigc.net/v1",
    credentialEnvVar: "QIHANG_API_KEY",
    doc: "https://www.qhaigc.net/docs",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "gemini-2.5-flash",
      "gemini-3-flash-preview",
      "gpt-5.2",
      "gpt-5.2-codex",
      "gemini-3-pro-preview",
    ],
  },
  {
    id: "qiniu-ai",
    name: "Qiniu",
    baseURL: "https://api.qnaigc.com/v1",
    credentialEnvVar: "QINIU_API_KEY",
    doc: "https://developer.qiniu.com/aitokenapi",
    capabilities: ["reasoning", "toolCalling", "imageInput"],
    knownModels: [
      "qwen3.5-397b-a17b",
      "doubao-seed-2.0-code",
      "doubao-seed-2.0-lite",
      "doubao-seed-2.0-mini",
      "doubao-seed-2.0-pro",
    ],
  },
  {
    id: "regolo-ai",
    name: "Regolo AI",
    baseURL: "https://api.regolo.ai/v1",
    credentialEnvVar: "REGOLO_API_KEY",
    doc: "https://docs.regolo.ai/",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "qwen3.8-27b",
      "glm5.2",
      "gemma4-31b",
      "mistral-small-4-119b",
      "gpt-oss-20b",
    ],
  },
  {
    id: "requesty",
    name: "Requesty",
    baseURL: "https://router.requesty.ai/v1",
    credentialEnvVar: "REQUESTY_API_KEY",
    doc: "https://requesty.ai/solution/llm-routing/models",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "claude-haiku-5-5",
      "claude-haiku-5-5@eu",
      "mistral-large-4",
      "mistral-large-4@eu",
      "gpt-6.1-sol",
    ],
  },
  {
    id: "routing-run",
    name: "routing.run",
    baseURL: "https://api.routing.run/v1",
    credentialEnvVar: "ROUTING_RUN_API_KEY",
    doc: "https://docs.routing.run/api-reference/models",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "gpt-5.6-luna",
      "gpt-5.6-sol",
      "gpt-5.6-terra",
      "glm-5.2",
      "glm-5.2-nitro",
    ],
  },
  {
    id: "runinfra",
    name: "RunInfra",
    baseURL: "https://api.runinfra.ai/v1",
    credentialEnvVar: "RUNINFRA_GATEWAY_KEY",
    doc: "https://runinfra.ai/docs",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "zai-org/GLM-5.3-Flash",
      "ornith-ai/Ornith-1.5-35B-A3B",
      "Qwen/Qwen3.8-27B",
      "deepseek-ai/DeepSeek-V4-Pro-0813",
      "Inferact/Qwen3.8-2.4T-A95B-NVFP4",
    ],
  },
  {
    id: "sakana",
    name: "Sakana AI",
    baseURL: "https://api.sakana.ai/v1",
    credentialEnvVar: "SAKANA_API_KEY",
    doc: "https://console.sakana.ai/models",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "sakana-namazu",
      "fugu",
      "fugu-ultra",
      "fugu-ultra-20260615",
    ],
  },
  {
    id: "sarvam",
    name: "Sarvam AI",
    baseURL: "https://api.sarvam.ai/v1",
    credentialEnvVar: "SARVAM_API_KEY",
    doc: "https://docs.sarvam.ai/api-reference-docs/getting-started/models",
    capabilities: ["reasoning", "toolCalling"],
    knownModels: [
      "sarvam-105b",
      "sarvam-30b",
    ],
  },
  {
    id: "scaleway",
    name: "Scaleway",
    baseURL: "https://api.scaleway.ai/v1",
    credentialEnvVar: "SCALEWAY_API_KEY",
    doc: "https://www.scaleway.com/en/docs/generative-apis/",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "qwen3.8-27b",
      "deepseek-v4-flash-0731",
      "glm-5.2",
      "qwen3.6-35b-a3b",
      "mistral-medium-3.5-128b",
    ],
  },
  {
    id: "scnet-token-plan",
    name: "SCNet Token Plan",
    baseURL: "https://api.scnet.cn/api/llm/v1",
    credentialEnvVar: "SCNET_API_KEY",
    doc: "https://www.scnet.cn/ac/openapi/doc/2.0/moduleapi/plans/token-plan.html",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "DeepSeek-V4.1-Flash",
      "GLM-5.3-Flash",
      "Qwen3.8-Flash",
      "GLM-5.3",
      "DeepSeek-V4-Pro-0813",
    ],
  },
  {
    id: "scx-ai",
    name: "SCX.ai",
    baseURL: "https://api.scx.ai/v1",
    credentialEnvVar: "SCX_API_KEY",
    doc: "https://platform.scx.ai/docs",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "Qwen3.8-Max",
      "GLM-5.2",
      "MiniMax-M2.7",
      "gpt-oss-120b",
    ],
  },
  {
    id: "sensenova",
    name: "SenseNova (China)",
    baseURL: "https://token.sensenova.cn/v1",
    credentialEnvVar: "SENSENOVA_API_KEY",
    doc: "https://platform.sensenova.cn/docs",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "deepseek-v4-pro",
      "sensenova-6.8-flash-lite",
      "kimi-k3",
      "glm-5.2",
      "deepseek-v4-flash",
    ],
  },
  {
    id: "siliconflow",
    name: "SiliconFlow",
    baseURL: "https://api.siliconflow.com/v1",
    credentialEnvVar: "SILICONFLOW_API_KEY",
    doc: "https://cloud.siliconflow.com/models",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "zai-org/GLM-5.3-Flash",
      "deepseek-ai/DeepSeek-V4-Flash-Vision-Exp",
      "zai-org/GLM-5.3",
      "deepseek-ai/DeepSeek-V4-Pro-0813",
      "Qwen/Qwen3.8-2.4T-A95B",
    ],
  },
  {
    id: "siliconflow-cn",
    name: "SiliconFlow (China)",
    baseURL: "https://api.siliconflow.cn/v1",
    credentialEnvVar: "SILICONFLOW_CN_API_KEY",
    doc: "https://cloud.siliconflow.com/models",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "zai-org/GLM-5.2",
      "deepseek-ai/DeepSeek-V4-Flash",
      "deepseek-ai/DeepSeek-V4-Pro",
      "Pro/moonshotai/Kimi-K2.6",
      "Qwen/Qwen3.6-35B-A3B",
    ],
  },
  {
    id: "stackit",
    name: "STACKIT",
    baseURL: "https://api.openai-compat.model-serving.eu01.onstackit.cloud/v1",
    credentialEnvVar: "STACKIT_API_KEY",
    doc: "https://docs.stackit.cloud/products/data-and-ai/ai-model-serving/basics/available-shared-models",
    capabilities: ["reasoning", "toolCalling", "imageInput"],
    knownModels: [
      "Qwen/Qwen3.6-27B",
      "Qwen/Qwen3-VL-Embedding-8B",
      "openai/gpt-oss-120b",
      "openai/gpt-oss-20b",
      "google/gemma-3-27b-it",
    ],
  },
  {
    id: "standardcompute",
    name: "Standard Compute",
    baseURL: "https://api.stdcmpt.com/v1",
    credentialEnvVar: "STANDARDCOMPUTE_API_KEY",
    doc: "https://standardcompute.com/models",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "standardcompute",
    ],
  },
  {
    id: "stepfun",
    name: "StepFun (China)",
    baseURL: "https://api.stepfun.com/v1",
    credentialEnvVar: "STEPFUN_API_KEY",
    doc: "https://platform.stepfun.com/docs/zh/overview/concept",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "step-5-preview",
      "step-3.7-flash",
      "stepaudio-2.5-asr",
      "step-3.5-flash-2603",
      "step-3.5-flash",
    ],
  },
  {
    id: "stepfun-ai",
    name: "StepFun (Global)",
    baseURL: "https://api.stepfun.ai/v1",
    credentialEnvVar: "STEPFUN_AI_API_KEY",
    doc: "https://platform.stepfun.ai/docs/en/overview/concept",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "step-5-preview",
      "step-3.7-flash",
      "stepaudio-2.5-asr",
      "step-3.5-flash-2603",
      "step-3.5-flash",
    ],
  },
  {
    id: "stepfun-step-plan",
    name: "StepFun Step Plan (China)",
    baseURL: "https://api.stepfun.com/step_plan/v1",
    credentialEnvVar: "STEPFUN_STEP_PLAN_API_KEY",
    doc: "https://platform.stepfun.com/docs/zh/step-plan/integrations/reasoning-api",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "step-5-preview",
      "step-3.7-flash",
      "step-router-v1",
      "step-3.5-flash-2603",
      "step-3.5-flash",
    ],
  },
  {
    id: "stepfun-ai-step-plan",
    name: "StepFun Step Plan (Global)",
    baseURL: "https://api.stepfun.ai/step_plan/v1",
    credentialEnvVar: "STEPFUN_AI_STEP_PLAN_API_KEY",
    doc: "https://platform.stepfun.ai/docs/en/step-plan/integrations/reasoning-api",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "step-5-preview",
      "step-3.7-flash",
      "step-3.5-flash-2603",
      "step-3.5-flash",
    ],
  },
  {
    id: "submodel",
    name: "submodel",
    baseURL: "https://llm.submodel.ai/v1",
    credentialEnvVar: "SUBMODEL_INSTAGEN_ACCESS_KEY",
    doc: "https://submodel.gitbook.io",
    capabilities: ["reasoning", "toolCalling"],
    knownModels: [
      "deepseek-ai/DeepSeek-R1-0528",
      "deepseek-ai/DeepSeek-V3-0324",
      "deepseek-ai/DeepSeek-V3.1",
      "openai/gpt-oss-120b",
      "Qwen/Qwen3-235B-A22B-Instruct-2507",
    ],
  },
  {
    id: "synthetic",
    name: "Synthetic",
    baseURL: "https://api.synthetic.new/openai/v1",
    credentialEnvVar: "SYNTHETIC_API_KEY",
    doc: "https://synthetic.new/pricing",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "hf:deepseek-ai/DeepSeek-V4.1-Flash",
      "hf:zai-org/GLM-5.3-Flash",
      "hf:zai-org/GLM-5.3",
      "hf:moonshotai/Kimi-K3",
      "hf:zai-org/GLM-5.2",
    ],
  },
  {
    id: "tempr",
    name: "Tempr Gateway",
    baseURL: "https://api.temprhq.io/v1",
    credentialEnvVar: "TEMPR_API_KEY",
    doc: "https://temprhq.io/docs/gateway-reference.html",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "xiaomi-mimo/mimo-v2.6-flash",
      "xiaomi-mimo/mimo-v2.6-pro",
      "xai/grok-4.7",
      "xiaomi-mimo/mimo-v2.6-pro-ultraspeed",
      "zai/glm-5.3-flashx",
    ],
  },
  {
    id: "tencent-coding-plan",
    name: "Tencent Coding Plan (China)",
    baseURL: "https://api.lkeap.cloud.tencent.com/coding/v3",
    credentialEnvVar: "TENCENT_CODING_PLAN_API_KEY",
    doc: "https://cloud.tencent.com/document/product/1772/128947",
    capabilities: ["reasoning", "toolCalling", "imageInput"],
    knownModels: [
      "hunyuan-2.0-instruct",
      "hunyuan-2.0-thinking",
      "hunyuan-t1",
      "hunyuan-turbos",
      "tc-code-latest",
    ],
  },
  {
    id: "tencent-token-plan",
    name: "Tencent Token Plan",
    baseURL: "https://api.lkeap.cloud.tencent.com/plan/v3",
    credentialEnvVar: "TENCENT_TOKEN_PLAN_API_KEY",
    doc: "https://cloud.tencent.com/document/product/1823/130060",
    capabilities: ["reasoning", "toolCalling"],
    knownModels: [
      "hy4-preview",
      "hy3",
    ],
  },
  {
    id: "tencent-tokenhub",
    name: "Tencent TokenHub",
    baseURL: "https://tokenhub.tencentmaas.com/v1",
    credentialEnvVar: "TENCENT_TOKENHUB_API_KEY",
    doc: "https://cloud.tencent.com/document/product/1823/130050",
    capabilities: ["reasoning", "toolCalling"],
    knownModels: [
      "hy4-preview",
      "hy3",
      "hy3-preview",
    ],
  },
  {
    id: "tensorx",
    name: "TensorX",
    baseURL: "https://api.tensorx.ai/v1",
    credentialEnvVar: "TENSORX_API_KEY",
    doc: "https://docs.tensorx.ai/",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "deepseek/deepseek-v4.1-flash",
      "qwen/qwen3.8-flash-next",
      "z-ai/glm-5.3-flash",
      "qwen/qwen3.8-27b",
      "z-ai/glm-5.3",
    ],
  },
  {
    id: "the-grid-ai",
    name: "The Grid AI",
    baseURL: "https://api.thegrid.ai/v1",
    credentialEnvVar: "THEGRID_API_KEY",
    doc: "https://thegrid.ai/docs",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "bytedance-pro-latest",
      "claude-opus-latest",
      "deepseek-pro-latest",
      "gemini-pro-latest",
      "glm-latest",
    ],
  },
  {
    id: "tinfoil",
    name: "Tinfoil",
    baseURL: "https://inference.tinfoil.sh/v1",
    credentialEnvVar: "TINFOIL_API_KEY",
    doc: "https://docs.tinfoil.sh",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "deepseek-v4-1-flash",
      "glm-5-3-flash",
      "glm-5-3",
      "kimi-k3",
      "gemma4-31b",
    ],
  },
  {
    id: "tokengo",
    name: "TokenGo",
    baseURL: "https://api.tokengo.com/v1",
    credentialEnvVar: "TOKENGO_API_KEY",
    doc: "https://www.tokengo.com/docs",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "z-ai/glm-5.3-flash",
      "z-ai/glm-5.3",
      "moonshotai/kimi-k3",
      "z-ai/glm-5.2",
      "deepseek/deepseek-v4-flash",
    ],
  },
  {
    id: "tokenrouter",
    name: "TokenRouter",
    baseURL: "https://api.tokenrouter.com/v1",
    credentialEnvVar: "TOKENROUTER_API_KEY",
    doc: "https://www.tokenrouter.com/docs/tokenrouter-feature-guide/",
    capabilities: ["reasoning", "toolCalling", "structuredOutput"],
    knownModels: [
      "z-ai/glm-5.3-free",
    ],
  },
  {
    id: "trustedrouter",
    name: "TrustedRouter",
    baseURL: "https://api.trustedrouter.com/v1",
    credentialEnvVar: "TRUSTEDROUTER_API_KEY",
    doc: "https://trustedrouter.com/docs",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "trustedrouter/synth",
      "trustedrouter/synth-code",
      "trustedrouter/e2e",
      "trustedrouter/fast",
      "trustedrouter/zdr",
    ],
  },
  {
    id: "umans-ai",
    name: "Umans AI",
    baseURL: "https://api.code.umans.ai/v1",
    credentialEnvVar: "UMANS_AI_API_KEY",
    doc: "https://app.umans.ai/offers/code/docs/orgs",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "umans-deepseek-v4.1-flash",
      "umans-coder",
      "umans-glm-5.3-flash",
      "umans-glm-5.3",
      "umans-deepseek-v4-flash-0731",
    ],
  },
  {
    id: "umans-ai-coding-plan",
    name: "Umans AI Coding Plan",
    baseURL: "https://api.code.umans.ai/v1",
    credentialEnvVar: "UMANS_AI_CODING_PLAN_API_KEY",
    doc: "https://app.umans.ai/offers/code/docs",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "umans-deepseek-v4.1-flash",
      "umans-coder",
      "umans-glm-5.3-flash",
      "umans-glm-5.3",
      "umans-deepseek-v4-flash-0731",
    ],
  },
  {
    id: "unorouter",
    name: "UnoRouter",
    baseURL: "https://api.unorouter.com/v1",
    credentialEnvVar: "UNOROUTER_API_KEY",
    doc: "https://unorouter.com/models",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "claude-sonnet-5",
      "glm-5.2",
      "glm-5.2:free",
      "nemotron-3-ultra-550b-a55b:free",
      "step-3.7-flash:free",
    ],
  },
  {
    id: "upstage",
    name: "Upstage",
    baseURL: "https://api.upstage.ai/v1/solar",
    credentialEnvVar: "UPSTAGE_API_KEY",
    doc: "https://developers.upstage.ai/docs/apis/chat",
    capabilities: ["reasoning", "toolCalling", "structuredOutput"],
    knownModels: [
      "solar-pro4",
      "solar-pro3",
      "solar-pro2",
      "solar-mini",
    ],
  },
  {
    id: "vancine",
    name: "Vancine",
    baseURL: "https://vancine.com/v1",
    credentialEnvVar: "VANCINE_API_KEY",
    doc: "https://vancine.com/docs",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "deepseek-v4.1-flash",
      "hy4-preview",
      "glm-5.3-flash",
      "qwen3.8-flash",
      "glm-5.3",
    ],
  },
  {
    id: "vispark",
    name: "Vispark",
    baseURL: "https://api.lab.vispark.in/v1",
    credentialEnvVar: "VISPARK_LAB_API_KEY",
    doc: "https://lab.vispark.in/#vision",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "vispark/vision-large",
      "vispark/vision-medium",
      "vispark/vision-small",
    ],
  },
  {
    id: "vivgrid",
    name: "Vivgrid",
    baseURL: "https://api.vivgrid.com/v1",
    credentialEnvVar: "VIVGRID_API_KEY",
    doc: "https://docs.vivgrid.com/models",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "claude-haiku-5-5",
      "gpt-6.1-sol",
      "claude-sonnet-5-5",
      "claude-opus-5-5",
      "gpt-6-luna",
    ],
  },
  {
    id: "volcengine",
    name: "Volcengine Ark",
    baseURL: "https://ark.cn-beijing.volces.com/api/v3",
    credentialEnvVar: "ARK_API_KEY",
    doc: "https://www.volcengine.com/docs/82379/1330310",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "glm-5-3-flash-260828",
      "deepseek-v4-pro-ga-260813",
      "deepseek-v4-flash-ga-260731",
      "doubao-seed-2-1-pro-260628",
      "doubao-seed-2-1-turbo-260628",
    ],
  },
  {
    id: "volcengine-coding-plan",
    name: "Volcengine Ark Coding Plan",
    baseURL: "https://ark.cn-beijing.volces.com/api/coding/v3",
    credentialEnvVar: "ARK_CODING_PLAN_API_KEY",
    doc: "https://www.volcengine.com/docs/82379/1928261",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "glm-5.3-flash",
      "glm-5.3",
      "kimi-k3",
      "doubao-seed-2.1-turbo",
      "doubao-seed-evolving",
    ],
  },
  {
    id: "vultr",
    name: "Vultr",
    baseURL: "https://api.vultrinference.com/v1",
    credentialEnvVar: "VULTR_API_KEY",
    doc: "https://api.vultrinference.com/",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "mimo-v2.6-flash-rl",
      "mimo-v2.6-pro-rl",
      "deepseek-v4.1-flash",
      "qwen3.8-flash-next",
      "glm-5.3-flash",
    ],
  },
  {
    id: "wafer.ai",
    name: "Wafer",
    baseURL: "https://pass.wafer.ai/v1",
    credentialEnvVar: "WAFER_API_KEY",
    doc: "https://docs.wafer.ai/wafer-pass",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "GLM-5.2",
      "glm5.2-fast",
      "MiniMax-M3",
      "Kimi-K2.6",
      "GLM-5.1",
    ],
  },
  {
    id: "wallaby",
    name: "Wallaby",
    baseURL: "https://api.wallabytoken.com/v1",
    credentialEnvVar: "WALLABY_API_KEY",
    doc: "https://wallabytoken.com/docs",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "moonshotai/kimi-k3",
    ],
  },
  {
    id: "xiaomi",
    name: "Xiaomi",
    baseURL: "https://api.xiaomimimo.com/v1",
    credentialEnvVar: "XIAOMI_API_KEY",
    doc: "https://platform.xiaomimimo.com/#/docs",
    capabilities: ["reasoning", "toolCalling", "imageInput"],
    knownModels: [
      "mimo-v2.6-flash",
      "mimo-v2.6-pro",
      "mimo-v2.6-pro-ultraspeed",
      "mimo-v2.5-pro-ultraspeed",
      "mimo-v2.5",
    ],
  },
  {
    id: "xiaomi-token-plan-cn",
    name: "Xiaomi Token Plan (China)",
    baseURL: "https://token-plan-cn.xiaomimimo.com/v1",
    credentialEnvVar: "XIAOMI_TOKEN_PLAN_CN_API_KEY",
    doc: "https://platform.xiaomimimo.com/#/docs",
    capabilities: ["reasoning", "toolCalling", "imageInput"],
    knownModels: [
      "mimo-v2.6-flash",
      "mimo-v2.6-pro",
      "mimo-v2.5",
      "mimo-v2.5-pro",
      "mimo-v2-pro",
    ],
  },
  {
    id: "xiaomi-token-plan-ams",
    name: "Xiaomi Token Plan (Europe)",
    baseURL: "https://token-plan-ams.xiaomimimo.com/v1",
    credentialEnvVar: "XIAOMI_TOKEN_PLAN_AMS_API_KEY",
    doc: "https://platform.xiaomimimo.com/#/docs",
    capabilities: ["reasoning", "toolCalling", "imageInput"],
    knownModels: [
      "mimo-v2.6-flash",
      "mimo-v2.6-pro",
      "mimo-v2.5",
      "mimo-v2.5-pro",
      "mimo-v2-pro",
    ],
  },
  {
    id: "xiaomi-token-plan-sgp",
    name: "Xiaomi Token Plan (Singapore)",
    baseURL: "https://token-plan-sgp.xiaomimimo.com/v1",
    credentialEnvVar: "XIAOMI_TOKEN_PLAN_SGP_API_KEY",
    doc: "https://platform.xiaomimimo.com/#/docs",
    capabilities: ["reasoning", "toolCalling", "imageInput"],
    knownModels: [
      "mimo-v2.6-flash",
      "mimo-v2.6-pro",
      "mimo-v2.5",
      "mimo-v2.5-pro",
      "mimo-v2-pro",
    ],
  },
  {
    id: "xpersona",
    name: "Xpersona",
    baseURL: "https://www.xpersona.co/v1",
    credentialEnvVar: "XPERSONA_API_KEY",
    doc: "https://www.xpersona.co/docs",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "gpt-5.6",
      "gpt-5.6-sol",
      "gpt-5.6-terra",
      "claude-fable-5",
      "xpersona-gpt-5.5",
    ],
  },
  {
    id: "zai",
    name: "Z.AI",
    baseURL: "https://api.z.ai/api/paas/v4",
    credentialEnvVar: "ZAI_API_KEY",
    doc: "https://docs.z.ai/guides/overview/pricing",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "glm-5.3-flashx",
      "glm-5.3-flash",
      "glm-5.3",
      "glm-5.2",
      "glm-5.1",
    ],
  },
  {
    id: "zai-coding-plan",
    name: "Z.AI Coding Plan",
    baseURL: "https://api.z.ai/api/coding/paas/v4",
    credentialEnvVar: "ZAI_CODING_PLAN_API_KEY",
    doc: "https://docs.z.ai/devpack/overview",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "glm-5.3-flash",
      "glm-5.3",
      "glm-5.3-highspeed",
      "glm-5.2",
      "glm-5.2-highspeed",
    ],
  },
  {
    id: "zeldoc",
    name: "Zeldoc",
    baseURL: "https://api.zeldoc.ai/v1",
    credentialEnvVar: "ZELDOC_API_KEY",
    doc: "https://docs.zeldoc.ai",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "zdev",
    ],
  },
  {
    id: "zenifra",
    name: "Zenifra",
    baseURL: "https://ai.zenifra.com/v1",
    credentialEnvVar: "ZENIFRA_AI_KEY",
    doc: "https://docs.zenifra.com",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "alibaba/qwen3.6-35b-a3b",
    ],
  },
  {
    id: "zenmux",
    name: "ZenMux",
    baseURL: "https://zenmux.ai/api/v1",
    credentialEnvVar: "ZENMUX_API_KEY",
    doc: "https://docs.zenmux.ai",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "anthropic/claude-opus-5.5",
      "openai/gpt-6-sol",
      "xiaomi/mimo-v2.6-pro",
      "deepseek/deepseek-v4.1-flash",
      "openai/gpt-6-astra",
    ],
  },
  {
    id: "zhipuai",
    name: "Zhipu AI",
    baseURL: "https://open.bigmodel.cn/api/paas/v4",
    credentialEnvVar: "ZHIPUAI_API_KEY",
    doc: "https://docs.z.ai/guides/overview/pricing",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "glm-5.3-flashx",
      "glm-5.3-flash",
      "glm-5.3",
      "glm-5.2",
      "glm-5v-turbo",
    ],
  },
  {
    id: "zhipuai-coding-plan",
    name: "Zhipu AI Coding Plan",
    baseURL: "https://open.bigmodel.cn/api/coding/paas/v4",
    credentialEnvVar: "ZHIPUAI_CODING_PLAN_API_KEY",
    doc: "https://docs.bigmodel.cn/cn/coding-plan/overview",
    capabilities: ["reasoning", "toolCalling", "imageInput", "structuredOutput"],
    knownModels: [
      "glm-5.3-flash",
      "glm-5.3",
      "glm-5.3-highspeed",
      "glm-4.6v",
    ],
  },
];
